[package]
name = "serde-bin-prot"
version = "0.1.0"
authors = ["Willem Olding <willemolding@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125" }
shrinkwraprs = "0.3.0"

[dev-dependencies]
regex = { version = "1" }
