name: Build and Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - run: cargo test
      - run: cargo fmt -- --check
